# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c28aa26d8407e2c4bfb2a8d10b2e5c8285e74468dc4b82005a4ed0b2dd2f9adeef19b337a5e33025c4673da1323aefa2909c88e6b905b60ed72fa7eebbc1b010

test:
  secret_key_base: 268267d5cb479a529c0d8ddf08b42713ea5acf8ceb696232f5c9688498cf81f5e65537004922083088675bd0aabbb509ed34aaa0a321acf2a3b012186b42b583

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
